<template>
  <div>
      <v-hover style="width: 1000px">
        <template v-slot="{ hover }">
          <div class="mx-auto">
            <div class="mx-auto bg-info" style="width: 500px;">
              <v-card :elevation="hover ? 24 : 6" color="indigo lighten-2" dark>
                <v-card-title class="headline indigo lighten-1">Search for Doctor</v-card-title>
                <v-card-text>
                  <v-expand-transition>
                     <v-row>
                    <v-col cols="12">
                      <v-combobox
                        v-model="model"
                        :items="search"
                        label="Type your health problem"
                      ></v-combobox>
                    </v-col>
                  </v-row>
                  </v-expand-transition>
                 
                </v-card-text>
               
                <v-card-actions>
                  <v-btn :disabled="!model" color="grey darken-3" @click="model=null">
                    Clear
                    <v-icon right>mdi-close-circle</v-icon>
                  </v-btn>
                  <v-spacer></v-spacer>
                  <v-btn :disabled="!model">
                    <router-link to="/SearchResult">Search</router-link>
                    <v-icon right>mdi-magnify</v-icon>
                  </v-btn>
                </v-card-actions>
              </v-card>
            </div>
          </div>
        </template>
      </v-hover>

   
  </div>
</template>

<script>
//import axios from 'axios';

export default {
  components: {
    
  },
  data() {
    return {
      //searchSet:[],
      descriptionLimit: 60,
      entries: [],
  
      model: null,
      search: null,
     
      search: [
        "Acne",
        "Allergic Cough",
        "Allergic Eye Problems",
        "Allergic Itch",
        "Allergic Rash",
        "Arm/Hand Pain",
        "Asthma",
        "Asthma Symptoms",
        "Athlete's Foot",
        "Athlete's Foot",
        "Back & Neck & Shoulder Pain",
        "Bad Breath",
        "Blistering of Skin",
        "Breast Exam",
        "Changes in Taste",
        "Cold Sores",
        "Common Cold",
        "Congestion",
        "Diarrhea",
        "Dizziness/Lightheadedness",
        "Drug Allergy",
        "Dry Skin",
        "Ear Discharge",
        "Ear Infection",
        "Ear Pain/Earache",
        "Ear Pressure",
        "Ear Problems",
        "Eczema Symptoms",
        "Excessive Hunger",
        "Family Planning",
        "Fever",
        "Food Allergy",
        "Food Allergy/Intolerance",
        "Frequent Urination",
        "Hay Fever/Seasonal Allergies",
        "Headache",
        "Headaches",
        "Hip Pain",
        "Hives",
        "Injections",
        "Lab Services",
        "Leg/Foot Pain",
        "Mole Discoloration",
        "Mole Growth",
        "Muffled Hearing",
        "Muscle Spasms",
        "Neck Pain",
        "Newborn and Well-Child Care",
        "Obesity",
        "Oily Skin",
        "Pelvic Exam & Pap Smear",
        "Pelvic Exam & Pap Smear",
        "Physical Exams",
        "Poison Oak",
        "Poison Oak/Ivy",
        "Poor Equilibrium/Balance",
        "Rash",
        "Ringing/Buzzing in Ears",
        "Shoulder Pain",
        "Sunburn",
        "Unusual/Excessive Thirst",
        "Vaccinations",
        "Back Pain",
        "Bone Symptoms/Condition",
        "Concussion",
        "Delirium",
        "Enlarged Prostate",
        "Fracture",
        "Fractured Facial Bones",
        "Fractured Jaw",
        "Hallucinations",
        "Kidney Stones",
        "Muscle Pull/Strain/Tear",
        "Bed-Wetting",
        "Circadian Rhythm Disorders",
        "Insomnia",
        "Narcolepsy",
        "Night Sweats",
        "Night Terrors",
        "Nightmares",
        "Sleep Apnea",
        "Sleepwalking",
        "Snoring",
        "Allergies",
        "Ankle Pain",
        "Arch Pain",
        "Arthritis Related Symptoms",
        "Bone Symptoms",
        "Cancer",
        "Chronic Pain",
        "Diabetes",
        "Diet Education",
        "Digestive Problems",
        "Food Alergies",
        "Foot Pain",
        "Hand Pain",
        "Hormonal Imbalances",
        "Immobility",
        "Infertility",
        "Joint Instability",
        "Joint Pain",
        "Joint Stiffness",
        "Mood Changes",
        "Muscle Cramps",
        "Muscle Pain",
        "Muscle Weakness",
        "Nutritional Issues",
        "Osteoporosis",
        "Overweight",
        "Restless Legs",
        "Stiff Neck",
        "Weight Fluctuation",
        "Weight Loss",
        "AIDS",
        "Allergy",
        "Anemia",
        "Arthritis",
        "Autism",
        "Breast cancer",
        "Hepatitis",
        "HIV",
        "Pneumonia",
        "Psoriasis",
        "Tumor",
        "Muscle Stiffness",
        "Stress",
        "Tennis Elbow",
        "Walking Problems",
        "Alzheimer's Disease",
        "Coronary Artery Disease",
        "Dementia",
        "Hyperthyroidism",
        "Strokes",
        "Tumors",
        "Anemic Symptoms",
        "Blood Disorder Symptoms",
        "Chronic Nosebleed",
        "Hemophilia",
        "HIV/AIDS Symptoms",
        "Leukemia",
        "Lymphoma",
        "Myeloma",
        "Sickle Cell Disease",
        "Cystic Fibrosis",
        "Diabetic Foot Symptoms",
        "Double Vision",
        "Exhaustion",
        "Extreme Fatigue/Irritability",
        "Hair Loss",
        "Hormonal Changes",
        "Hyperactivity",
        "Hypertension",
        "Impotence",
        "Loss of Taste",
        "Menopause",
        "Pituitary Problems",
        "Postmenopausal Symptoms",
        "Sexual Complications",
        "Swollen Lymph Nodes",
        "Thyroid Symptoms",
        "Chest Pain",
        "Eye Discharge",
        "Frequent Infections",
        "Malaria Symptoms",
        "Meningitis Symptoms",
        "Pain During Intercourse",
        "Persistent Low-Grade Fever",
        "Renal Failure",
        "Tuberculosis Symptoms",
        "Articulation Problems",
        "Speech Problems",
        "Voice Disorders",
        "Anesthesia",
        "Pain Management",
        "Sedation",
        "Angina pectoris",
        "EKG",
        "Heart Disease",
        "Heart Problems",
        "Pacemaker",
        "Alcohol/tobacco Addiction",
        "Depression",
        "Drug Addiction",
        "Eating Disorder",
        "Smoking Cessation",
        "Substance Abuse",
        "Allergic Swelling",
        "Bumpy Eyelids",
        "Burning in Throat",
        "Coeliac Disease Symptoms",
        "Crusty Eyelids",
        "Difficulty Swallowing",
        "Dry Eyes",
        "Dry Mouth",
        "Dry or Itchy Throat",
        "Eye Sensitivity",
        "Hay Fever & Seasonal Allergies",
        "Hoarseness in Voice",
        "Itchy Eyes",
        "Itchy Skin",
        "Lactose Intolerance",
        "Measles Symptoms",
        "Persistent Cough",
        "Redness of Eyes",
        "Runny Nose",
        "Swollen Tongue",
        "Watery Eyes",
        "Wheezing",
        "Bleeding of Gums",
        "Chipped/Broken Tooth",
        "Crooked Teeth",
        "Jaw Irregularities",
        "Loose Tooth",
        "Lost/Missing Teeth\nBad Breath",
        "Overbite",
        "Painful Chewing",
        "Painful Swallowing",
        "Receeding Gums",
        "Sensitive Teeth",
        "Sore Gums",
        "Swelling of Gums",
        "Teeth Sensitivity",
        "Temporomandibular Joint Disorders (TMJ)",
        "Tooth Discoloration",
        "Tooth Pain",
        "Toothache",
        "Underbite",
        "Unequal Jaw Growth",
        "Wisdom Teeth",
        "Brain Tumors",
        "Cervical Spinal Stenosis",
        "Head Trauma",
        "Hydrocephalus",
        "Infections",
        "Lumbar Spinal Stenosis",
        "Spinal Cord Trauma",
        "Spinal Disc Herniation",
        "Spine Tumors",
        "Traumatic Injuries of Peripheral Nerves",
        "ADHD",
        "Anger Problems",
        "Anxiety",
        "Blacking Out",
        "Blurred Vision",
        "Cognitive Complications",
        "Confusion/Disorientation",
        "Deterioration of Vision",
        "Difficulty Concentrating",
        "Difficulty Speaking",
        "Excessive Perspiration",
        "Fainting (Syncope)",
        "Impaired Intellect",
        "Impaired Memory",
        "Learning Difficultes",
        "Loss of Smell",
        "Memory Loss",
        "Migraines",
        "Nervousness",
        "Panic Attacks",
        "Poor Balance",
        "Ringing in Ears",
        "Seizures",
        "Sensitivity to Light",
        "Shaky Hands",
        "Tremors",
        "Dyslipidemia",
        "Musculoskeletal Disorders",
        "Osteoarthritis",
        "Thyroid Disorders",
        "Wound Care",
        "Ankle/Foot Pain",
        "Arch Pain/Problems",
        "Birth Defects",
        "Bunions",
        "Calluses",
        "Heel Spurs",
        "Prosthetic Limb Complications",
        "Swollen Joints",
        "Bronchitis",
        "Chronic Cough",
        "Difficulty Breathing",
        "Hyperventilation",
        "Painful Breathing",
        "Phlegm/Mucus Buildup",
        "Pneumonia Related Symptoms",
        "Shortness of Breath",
        "Strained Breathing",
        "Tuberculosis",
        "Uncontrollable Sneezing Fits",
        "Abcess",
        "Abdominal Bulge",
        "Black Stool",
        "Black Stool/Melena",
        "Blood or Mucus in Stool",
        "Cardiac Electrophysiology",
        "Cardiac Surgery",
        "Cardiag Surgery",
        "Cardiology",
        "Cleft Lip/Palate",
        "Constipation",
        "Deviated Septum",
        "Facial Infection",
        "Gastrointestinal Symptoms",
        "Head Tilt",
        "Heart Surgery",
        "Heart Transplant",
        "Hemorrhoids",
        "Interventional Cardiology",
        "Knee pain",
        "Loss of Appetite",
        "Lung Transplant",
        "Missing Testicle",
        "Rectal Bleeding",
        "Rectal Pain",
        "Spider Veins",
        "Sunken Soft Spots on Head",
        "Swollen Tonsils",
        "Thoracic Surgery",
        "Trauma Surgery",
        "Turned-in Foot",
        "Varicose Veins",
        "Wart Growth",
        "Deterioration/Loss of Vision",
        "Heartburn",
        "Inner Ear Disease Symptoms",
        "Nasal Symptoms",
        "Painful Swallowingl",
        "Post Nasal Drip",
        "Sleep Apnea (Snoring)",
        "Sore Throat",
        "Sudden or Gradual Hearing Loss",
        "Throat Symptoms",
        "Marriage Councelling",
        "School Councelling",
        "Critical Care",
        "Emergency care",
        "General Surgery",
        "Pulmonary Critical Care",
        "Ddigestive Problems",
        "Diabetes\nCancer",
        "Infectious Diseases",
        "Kidney Problems",
        "Lung and Airway Problems",
        "Medical issues in surgical patients",
        "Psychiatric Problems",
        "Stomach and Intestinal Problems",
        "Urinary Tract Problems",
        "Abdominal/Stomach Pain",
        "Abdominal Swelling/Bloating",
        "Eating Disorder Symptoms",
        "Excessive Belching",
        "Gas",
        "Unusual Weight Loss",
        "Celiac Diseases",
        "Chronic Liver Disease",
        "Cirrhosis",
        "Enzyme Deficiencies",
        "Gall Stones",
        "Jaundice",
        "Liver Cancer",
        "Pancreatic Cancer",
        "Heel Spurs\nJoint Pain",
        "Physical therapy",
        "Swelling of Legs/Ankles",
        "Blood in Semen",
        "Blood in Urine",
        "Cloudy Urine",
        "Decreased Sex Drive",
        "Erectile Dysfunction (Impotence)",
        "Foul-Smelling Urine",
        "Genital Sores",
        "Incontinence",
        "Male Infertility",
        "Overactive Bladder",
        "Painful Urination",
        "Premature Ejaculation",
        "Testicular Pain",
        "Urinary Tract Infection",
        "Birth Control",
        "Changes in Menstruation",
        "Frequent Menstruation",
        "Increased Menstrual Flow",
        "Intermenstrual Bleeding",
        "Less Frequent Menstruation",
        "Menopause Symptoms",
        "Menstrual Cramps",
        "Menstrual Pain",
        "Nausea",
        "Pap Test/Smear",
        "Pelvic Pain",
        "Postpartum Depression",
        "Pregnancy",
        "Premenopausal Symptoms",
        "Prenatal/Postnatal Nutrition",
        "Protein in Urine",
        "Vaginal Discomfort/Pain",
        "Vaginal Itching",
        "Vaginal Odor",
        "Yeast Infection",
        "Astigmatism",
        "Cataracts",
        "Color Blindness",
        "Corneal Abrasion (Scratch)",
        "Corneal Abrasion (Scratch)",
        "Eye Infection",
        "Glaucomal",
        "Swollen Eyes",
        "Tunnel Vision",
        "Blisters",
        "Bruising",
        "Foot Symptoms",
        "Sprain",
        "tendonitis",
        "Botox Teatment",
        "Brest Augmentation",
        "Deformed Ears",
        "Drooping Eyelids",
        "Facelift",
        "Sagging Skin",
        "Scar Removal",
        "Tumor Removal",
        "Wrinkles",
        "Leg Pain",
        "Muscle Pull",
        "Chronic Hearth Failure",
        "HIV/AIDS",
        "Life-threatening Illnesses",
        "Allergic Swelling/Inflammation",
        "Corns",
        "Dandruff",
        "Fingernail Discoloration",
        "DNA Screening",
        "Genetic Diseases",
        "Cataract",
        "Memory Problems",
        "Pain",
        "Rheumatism",
        "Sleeping Problems",
        "Malaria",
        "Measles",
        "Meningitis",
        "Vaginal Discharge",
        "Vomiting",
        "Fibromyalgia",
        "Goat",
        "Lupus",
        "Marfan's Syndrome",
        "Schleroderma",
        "bursitis",
        "motor vehicle accidents",
        "Multiple Sclerosis (MS)",
        "Neck and back pain",
        "Parkinson's",
        "pelvic and low back pain",
        "Sinusitis",
        "sprains",
        "strains",
        "trauma",
        "Vertigo",
        "Ccongenital Deformities",
        "Cleft Palate",
        "Head and Neck Cancer",
        "Reconstructive and Cosmetic Facial Surgery.",
        "Trauma-related Injuries",
        "Ingrown Toenail",
        "Physical Examination",
        "Preventinve Screening",
        "Vacconations Such as Flu Shots",
        "Workplace Safety",
        "Gout Symptoms",
        "Autopsy",
        "Lab Tests",
        "Test Blood/Tissue/Organ Samples",
        "Balance Problems",
        "Hearing Aid",
        "Hearing Loss",
        "Hearing Problems",
        "Dark Urine",
        "High Blood Pressure",
        "Kidney Disease",
        "Kidney Disease Symptoms",
        "ADD Symptoms",
        "ADHD Symptoms",
        "Alzheimer's Disease",
        "General Mental Health Symptoms",
        "Increased Appetite",
        "Manic Depression Symptoms",
        "Muteness",
        "Post Traumatic Stress Disorder Symptoms",
        "Separation Anxiety",
        "Slurred Speech",
        "Stuttering"
      ]
    
    };
  }

  /* methods:{
    search(){
      var key = document.getElementById('Search').value;
      
      axios.get("https://api.betterdoctor.com/2016-03-01/conditions?q="+key+"&fields=data%2Cname&limit=10&user_key=9203842f28dad80bbeb83418e860b019")
      .then(response=>{
        this.searchSet=response.data.data;
        //console.log(response.data.data)
        //his.key=response.data.data;
        

      })
      .catch(function (error) {
    // handle error
    console.log(error);
  })

 // this.$emit('newDataset',this.searchSet)
    }
  },*/
};
</script>



